package com.lovo.bean;

public class EventXuEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eventxu.pk_continue_id
     *
     * @mbggenerated
     */
	
    private Integer pkContinueId;

    public void setPkContinueId(Integer pkContinueId) {
		this.pkContinueId = pkContinueId;
	}

	public void setFkThingnum(String fkThingnum) {
		this.fkThingnum = fkThingnum;
	}

	public void setfAdress(String fAdress) {
		this.fAdress = fAdress;
	}

	public void setFkType(Integer fkType) {
		this.fkType = fkType;
	}

	public void setFkLevel(Integer fkLevel) {
		this.fkLevel = fkLevel;
	}

	public void setfAlarmpeople(String fAlarmpeople) {
		this.fAlarmpeople = fAlarmpeople;
	}

	public void setfAlarmphone(String fAlarmphone) {
		this.fAlarmphone = fAlarmphone;
	}

	public void setfContinuetime(String fContinuetime) {
		this.fContinuetime = fContinuetime;
	}

	public void setfArea(Float fArea) {
		this.fArea = fArea;
	}

	public void setfInjured(Integer fInjured) {
		this.fInjured = fInjured;
	}

	public void setfHousenum(Integer fHousenum) {
		this.fHousenum = fHousenum;
	}

	public void setfLossmoney(Float fLossmoney) {
		this.fLossmoney = fLossmoney;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eventxu.fk_thingNum
     *
     * @mbggenerated
     */
    private String fkThingnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eventxu.f_adress
     *
     * @mbggenerated
     */
    private String fAdress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eventxu.fk_type
     *
     * @mbggenerated
     */
    private Integer fkType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eventxu.fk_level
     *
     * @mbggenerated
     */
    private Integer fkLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eventxu.f_alarmPeople
     *
     * @mbggenerated
     */
    private String fAlarmpeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eventxu.f_alarmPhone
     *
     * @mbggenerated
     */
    private String fAlarmphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eventxu.f_continueTime
     *
     * @mbggenerated
     */
    private String fContinuetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eventxu.f_area
     *
     * @mbggenerated
     */
    private Float fArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eventxu.f_injured
     *
     * @mbggenerated
     */
    private Integer fInjured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eventxu.f_houseNum
     *
     * @mbggenerated
     */
    private Integer fHousenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eventxu.f_lossMoney
     *
     * @mbggenerated
     */
    private Float fLossmoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eventxu
     *
     * @mbggenerated
     */
    public EventXuEntity(Integer pkContinueId, String fkThingnum, String fAdress, Integer fkType, Integer fkLevel, String fAlarmpeople, String fAlarmphone, String fContinuetime, Float fArea, Integer fInjured, Integer fHousenum, Float fLossmoney) {
        this.pkContinueId = pkContinueId;
        this.fkThingnum = fkThingnum;
        this.fAdress = fAdress;
        this.fkType = fkType;
        this.fkLevel = fkLevel;
        this.fAlarmpeople = fAlarmpeople;
        this.fAlarmphone = fAlarmphone;
        this.fContinuetime = fContinuetime;
        this.fArea = fArea;
        this.fInjured = fInjured;
        this.fHousenum = fHousenum;
        this.fLossmoney = fLossmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eventxu.pk_continue_id
     *
     * @return the value of t_eventxu.pk_continue_id
     *
     * @mbggenerated
     */
    public Integer getPkContinueId() {
        return pkContinueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eventxu.fk_thingNum
     *
     * @return the value of t_eventxu.fk_thingNum
     *
     * @mbggenerated
     */
    public String getFkThingnum() {
        return fkThingnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eventxu.f_adress
     *
     * @return the value of t_eventxu.f_adress
     *
     * @mbggenerated
     */
    public String getfAdress() {
        return fAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eventxu.fk_type
     *
     * @return the value of t_eventxu.fk_type
     *
     * @mbggenerated
     */
    public Integer getFkType() {
        return fkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eventxu.fk_level
     *
     * @return the value of t_eventxu.fk_level
     *
     * @mbggenerated
     */
    public Integer getFkLevel() {
        return fkLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eventxu.f_alarmPeople
     *
     * @return the value of t_eventxu.f_alarmPeople
     *
     * @mbggenerated
     */
    public String getfAlarmpeople() {
        return fAlarmpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eventxu.f_alarmPhone
     *
     * @return the value of t_eventxu.f_alarmPhone
     *
     * @mbggenerated
     */
    public String getfAlarmphone() {
        return fAlarmphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eventxu.f_continueTime
     *
     * @return the value of t_eventxu.f_continueTime
     *
     * @mbggenerated
     */
    public String getfContinuetime() {
        return fContinuetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eventxu.f_area
     *
     * @return the value of t_eventxu.f_area
     *
     * @mbggenerated
     */
    public Float getfArea() {
        return fArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eventxu.f_injured
     *
     * @return the value of t_eventxu.f_injured
     *
     * @mbggenerated
     */
    public Integer getfInjured() {
        return fInjured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eventxu.f_houseNum
     *
     * @return the value of t_eventxu.f_houseNum
     *
     * @mbggenerated
     */
    public Integer getfHousenum() {
        return fHousenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eventxu.f_lossMoney
     *
     * @return the value of t_eventxu.f_lossMoney
     *
     * @mbggenerated
     */
    public Float getfLossmoney() {
        return fLossmoney;
    }
}