package com.lovo.bean;

public class EventEntity {
	
    public void setPkThingId(Integer pkThingId) {
		this.pkThingId = pkThingId;
	}

	public void setfThingnum(String fThingnum) {
		this.fThingnum = fThingnum;
	}

	public void setfName(String fName) {
		this.fName = fName;
	}

	public void setfField(String fField) {
		this.fField = fField;
	}

	public void setfAdress(String fAdress) {
		this.fAdress = fAdress;
	}

	public void setFkType(Integer fkType) {
		this.fkType = fkType;
	}

	public void setFkLevel(Integer fkLevel) {
		this.fkLevel = fkLevel;
	}

	public void setfReportpeople(String fReportpeople) {
		this.fReportpeople = fReportpeople;
	}

	public void setfAlarmpeople(String fAlarmpeople) {
		this.fAlarmpeople = fAlarmpeople;
	}

	public void setfAlarmphone(String fAlarmphone) {
		this.fAlarmphone = fAlarmphone;
	}

	public void setfOccurtime(String fOccurtime) {
		this.fOccurtime = fOccurtime;
	}

	public void setfStatus(String fStatus) {
		this.fStatus = fStatus;
	}

	public void setfArea(Float fArea) {
		this.fArea = fArea;
	}

	public void setfInjured(Integer fInjured) {
		this.fInjured = fInjured;
	}

	public void setfHousenum(Integer fHousenum) {
		this.fHousenum = fHousenum;
	}

	public void setfLossmoney(Float fLossmoney) {
		this.fLossmoney = fLossmoney;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event.pk_thing_id
     *
     * @mbggenerated
     */
    private Integer pkThingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event.f_thingNum
     *
     * @mbggenerated
     */
    private String fThingnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event.f_name
     *
     * @mbggenerated
     */
    private String fName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event.f_field
     *
     * @mbggenerated
     */
    private String fField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event.f_adress
     *
     * @mbggenerated
     */
    private String fAdress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event.fk_type
     *
     * @mbggenerated
     */
    private Integer fkType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event.fk_level
     *
     * @mbggenerated
     */
    private Integer fkLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event.f_reportPeople
     *
     * @mbggenerated
     */
    private String fReportpeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event.f_alarmPeople
     *
     * @mbggenerated
     */
    private String fAlarmpeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event.f_alarmPhone
     *
     * @mbggenerated
     */
    private String fAlarmphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event.f_occurTime
     *
     * @mbggenerated
     */
    private String fOccurtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event.f_status
     *
     * @mbggenerated
     */
    private String fStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event.f_area
     *
     * @mbggenerated
     */
    private Float fArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event.f_injured
     *
     * @mbggenerated
     */
    private Integer fInjured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event.f_houseNum
     *
     * @mbggenerated
     */
    private Integer fHousenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event.f_lossMoney
     *
     * @mbggenerated
     */
    private Float fLossmoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_event
     *
     * @mbggenerated
     */
    public EventEntity(Integer pkThingId, String fThingnum, String fName, String fField, String fAdress, Integer fkType, Integer fkLevel, String fReportpeople, String fAlarmpeople, String fAlarmphone, String fOccurtime, String fStatus, Float fArea, Integer fInjured, Integer fHousenum, Float fLossmoney) {
        this.pkThingId = pkThingId;
        this.fThingnum = fThingnum;
        this.fName = fName;
        this.fField = fField;
        this.fAdress = fAdress;
        this.fkType = fkType;
        this.fkLevel = fkLevel;
        this.fReportpeople = fReportpeople;
        this.fAlarmpeople = fAlarmpeople;
        this.fAlarmphone = fAlarmphone;
        this.fOccurtime = fOccurtime;
        this.fStatus = fStatus;
        this.fArea = fArea;
        this.fInjured = fInjured;
        this.fHousenum = fHousenum;
        this.fLossmoney = fLossmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event.pk_thing_id
     *
     * @return the value of t_event.pk_thing_id
     *
     * @mbggenerated
     */
    public Integer getPkThingId() {
        return pkThingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event.f_thingNum
     *
     * @return the value of t_event.f_thingNum
     *
     * @mbggenerated
     */
    public String getfThingnum() {
        return fThingnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event.f_name
     *
     * @return the value of t_event.f_name
     *
     * @mbggenerated
     */
    public String getfName() {
        return fName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event.f_field
     *
     * @return the value of t_event.f_field
     *
     * @mbggenerated
     */
    public String getfField() {
        return fField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event.f_adress
     *
     * @return the value of t_event.f_adress
     *
     * @mbggenerated
     */
    public String getfAdress() {
        return fAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event.fk_type
     *
     * @return the value of t_event.fk_type
     *
     * @mbggenerated
     */
    public Integer getFkType() {
        return fkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event.fk_level
     *
     * @return the value of t_event.fk_level
     *
     * @mbggenerated
     */
    public Integer getFkLevel() {
        return fkLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event.f_reportPeople
     *
     * @return the value of t_event.f_reportPeople
     *
     * @mbggenerated
     */
    public String getfReportpeople() {
        return fReportpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event.f_alarmPeople
     *
     * @return the value of t_event.f_alarmPeople
     *
     * @mbggenerated
     */
    public String getfAlarmpeople() {
        return fAlarmpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event.f_alarmPhone
     *
     * @return the value of t_event.f_alarmPhone
     *
     * @mbggenerated
     */
    public String getfAlarmphone() {
        return fAlarmphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event.f_occurTime
     *
     * @return the value of t_event.f_occurTime
     *
     * @mbggenerated
     */
    public String getfOccurtime() {
        return fOccurtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event.f_status
     *
     * @return the value of t_event.f_status
     *
     * @mbggenerated
     */
    public String getfStatus() {
        return fStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event.f_area
     *
     * @return the value of t_event.f_area
     *
     * @mbggenerated
     */
    public Float getfArea() {
        return fArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event.f_injured
     *
     * @return the value of t_event.f_injured
     *
     * @mbggenerated
     */
    public Integer getfInjured() {
        return fInjured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event.f_houseNum
     *
     * @return the value of t_event.f_houseNum
     *
     * @mbggenerated
     */
    public Integer getfHousenum() {
        return fHousenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event.f_lossMoney
     *
     * @return the value of t_event.f_lossMoney
     *
     * @mbggenerated
     */
    public Float getfLossmoney() {
        return fLossmoney;
    }
}