package com.lovo.bean;

public class ManageShowEntity {
	


	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manageshow.pk_tId
 branch 'master' of https://github.com/CodeFarmerWithoutFeelings/J163_1_3.git
     *
     * @mbggenerated
     */
    private Integer pkTid;

    /**
     *
     * 事件编号
     *
     * @mbggenerated
     */
    private String fkThingid;

    /**
     * This field was generated by MyBatis Generator.
     * 详情资源编号
     *
     * @mbggenerated
     */
    private String fkId;

     /**
        * 资源名称
     * 
     *
     * @mbggenerated
     */
    private String fHosname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manageshow.f_add
     *
     * @mbggenerated
     */
    private String fAdd;

    /**
     * 派出总人数
     * 
     *
     * @mbggenerated
     */
    private Integer fPeonum;

    /**
     * 派出总车数
     * 
     *
     * @mbggenerated
     */
    private Integer fCarnum;

    /**
     * 负责人
     * 
     *
     * @mbggenerated
     */
    private String fMainpeo;

    /**
     * 调派时间
     * 
     *
     * @mbggenerated
     */
    private String fTime;

    /**
     * 调度人
     * 
     *
     * @mbggenerated
     */
    private String fYardman;

    /**
     * 负责人电话
     *
     * @mbggenerated
     */
    private String fMainpeotel;

    /**
     *处理状态
     *
     * @mbggenerated
     */
    private String fDealtype;

    /**
     *资源类型
     *
     * @mbggenerated
     */
    private String fZytype;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manageshow
     *
     * @mbggenerated
     */
    public ManageShowEntity(Integer pkTid, String fkThingid, String fkId, String fHosname, String fAdd, Integer fPeonum, Integer fCarnum, String fMainpeo, String fTime, String fYardman, String fMainpeotel, String fDealtype, String fZytype) {
        this.pkTid = pkTid;
        this.fkThingid = fkThingid;
        this.fkId = fkId;
        this.fHosname = fHosname;
        this.fAdd = fAdd;
        this.fPeonum = fPeonum;
        this.fCarnum = fCarnum;
        this.fMainpeo = fMainpeo;
        this.fTime = fTime;
        this.fYardman = fYardman;
        this.fMainpeotel = fMainpeotel;
        this.fDealtype = fDealtype;
        this.fZytype = fZytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manageshow.pk_tId
     *
     * @return the value of t_manageshow.pk_tId
     *
     * @mbggenerated
     */
    public Integer getPkTid() {
        return pkTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manageshow.fk_thingId
     *
     * @return the value of t_manageshow.fk_thingId
     *
     * @mbggenerated
     */
    public String getFkThingid() {
        return fkThingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manageshow.fk_id
     *
     * @return the value of t_manageshow.fk_id
     *
     * @mbggenerated
     */
    public String getFkId() {
        return fkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manageshow.f_hosName
     *
     * @return the value of t_manageshow.f_hosName
     *
     * @mbggenerated
     */
    public String getfHosname() {
        return fHosname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manageshow.f_add
     *
     * @return the value of t_manageshow.f_add
     *
     * @mbggenerated
     */
    public String getfAdd() {
        return fAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manageshow.f_peoNum
     *
     * @return the value of t_manageshow.f_peoNum
     *
     * @mbggenerated
     */
    public Integer getfPeonum() {
        return fPeonum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manageshow.f_carNum
     *
     * @return the value of t_manageshow.f_carNum
     *
     * @mbggenerated
     */
    public Integer getfCarnum() {
        return fCarnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manageshow.f_mainPeo
     *
     * @return the value of t_manageshow.f_mainPeo
     *
     * @mbggenerated
     */
    public String getfMainpeo() {
        return fMainpeo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manageshow.f_time
     *
     * @return the value of t_manageshow.f_time
     *
     * @mbggenerated
     */
    public String getfTime() {
        return fTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manageshow.f_yardman
     *
     * @return the value of t_manageshow.f_yardman
     *
     * @mbggenerated
     */
    public String getfYardman() {
        return fYardman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manageshow.f_mainPeoTel
     *
     * @return the value of t_manageshow.f_mainPeoTel
     *
     * @mbggenerated
     */
    public String getfMainpeotel() {
        return fMainpeotel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manageshow.f_dealType
     *
     * @return the value of t_manageshow.f_dealType
     *
     * @mbggenerated
     */
    public String getfDealtype() {
        return fDealtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manageshow.f_zyType
     *
     * @return the value of t_manageshow.f_zyType
     *
     * @mbggenerated
     */
    public String getfZytype() {
        return fZytype;
    }

	public void setPkTid(Integer pkTid) {
		this.pkTid = pkTid;
	}

	public void setFkThingid(String fkThingid) {
		this.fkThingid = fkThingid;
	}

	public void setFkId(String fkId) {
		this.fkId = fkId;
	}

	public void setfHosname(String fHosname) {
		this.fHosname = fHosname;
	}

	public void setfAdd(String fAdd) {
		this.fAdd = fAdd;
	}

	public void setfPeonum(Integer fPeonum) {
		this.fPeonum = fPeonum;
	}

	public void setfCarnum(Integer fCarnum) {
		this.fCarnum = fCarnum;
	}

	public void setfMainpeo(String fMainpeo) {
		this.fMainpeo = fMainpeo;
	}

	public void setfTime(String fTime) {
		this.fTime = fTime;
	}

	public void setfYardman(String fYardman) {
		this.fYardman = fYardman;
	}

	public void setfMainpeotel(String fMainpeotel) {
		this.fMainpeotel = fMainpeotel;
	}

	public void setfDealtype(String fDealtype) {
		this.fDealtype = fDealtype;
	}

	public void setfZytype(String fZytype) {
		this.fZytype = fZytype;
	}
    
}