package com.lovo.bean;

import java.util.Date;

public class ManageEntity {
	


	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manage.f_zyxqId
     *
     * @mbggenerated
     */
    private Integer fZyxqid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manage.fk_zyId
     *
     * @mbggenerated
     */
    private String fkZyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manage.f_zyName
     *
     * @mbggenerated
     */
    private String fZyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manage.f_timeOut
     *
     * @mbggenerated
     */
    private String fTimeout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manage.f_timeBack
     *
     * @mbggenerated
     */
    private String fTimeback;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manage.f_zyStuse
     *
     * @mbggenerated
     */
    private String fZystuse;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage
     *
     * @mbggenerated
     */
    public ManageEntity(Integer fZyxqid, String fkZyid, String fZyname, String fTimeout, String fTimeback, String fZystuse) {
        this.fZyxqid = fZyxqid;
        this.fkZyid = fkZyid;
        this.fZyname = fZyname;
        this.fTimeout = fTimeout;
        this.fTimeback = fTimeback;
        this.fZystuse = fZystuse;
    }
    

    public ManageEntity() {
		super();
		// TODO Auto-generated constructor stub
	}


	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manage.f_zyxqId
     *
     * @return the value of t_manage.f_zyxqId
     *
     * @mbggenerated
     */
    public Integer getfZyxqid() {
        return fZyxqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manage.fk_zyId
     *
     * @return the value of t_manage.fk_zyId
     *
     * @mbggenerated
     */
    public String getFkZyid() {
        return fkZyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manage.f_zyName
     *
     * @return the value of t_manage.f_zyName
     *
     * @mbggenerated
     */
    public String getfZyname() {
        return fZyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manage.f_timeOut
     *
     * @return the value of t_manage.f_timeOut
     *
     * @mbggenerated
     */
    public String getfTimeout() {
        return fTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manage.f_timeBack
     *
     * @return the value of t_manage.f_timeBack
     *
     * @mbggenerated
     */
    public String getfTimeback() {
        return fTimeback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manage.f_zyStuse
     *
     * @return the value of t_manage.f_zyStuse
     *
     * @mbggenerated
     */
    public String getfZystuse() {
        return fZystuse;
    }

	public void setfZyxqid(Integer fZyxqid) {
		this.fZyxqid = fZyxqid;
	}

	public void setFkZyid(String fkZyid) {
		this.fkZyid = fkZyid;
	}

	public void setfZyname(String fZyname) {
		this.fZyname = fZyname;
	}

	public void setfTimeout(String fTimeout) {
		this.fTimeout = fTimeout;
	}

	public void setfTimeback(String fTimeback) {
		this.fTimeback = fTimeback;
	}

	public void setfZystuse(String fZystuse) {
		this.fZystuse = fZystuse;
	}
    
}