package com.lovo.bean;

public class ModelEntity {
    /**
     * 模板id
     * 
     *
     * @mbggenerated
     */
    private Integer fkMbid;

    /**
     * 模板名称
     * 
     *
     * @mbggenerated
     */
    private String fMbname;

    /**
     * 
     * 模板类型
     *
     * @mbggenerated
     */
    private String fMbtype;

    /**
     * 
     * 模板等级
     *
     * @mbggenerated
     */
    private String fMbrank;

    /**
     * 医生人数
     *
     *
     * @mbggenerated
     */
    private Integer fMbdocnum;

    /**
     * 救护车数量
     * 
     *
     * @mbggenerated
     */
    private Integer fMbambnum;

    /**
     * 
     * 消防员数量
     *
     * @mbggenerated
     */
    private Integer fMbfirnum;

    /**
     * 
     * 消防车数量
     *
     * @mbggenerated
     */
    private Integer fMbinfernum;

    /**
     * 
     * 模板制作人
     *
     * @mbggenerated
     */
    private String fMbmeaker;

    /**
     * 
     * 模板制作人电话
     *
     * @mbggenerated
     */
    private String fMbmakertel;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_model
     *
     * @mbggenerated
     */
    public ModelEntity(Integer fkMbid,String fMbname, String fMbtype, String fMbrank, Integer fMbdocnum, Integer fMbambnum, Integer fMbfirnum, Integer fMbinfernum, String fMbmeaker, String fMbmakertel) {
       this.fkMbid=fkMbid;
        this.fMbname = fMbname;
        this.fMbtype = fMbtype;
        this.fMbrank = fMbrank;
        this.fMbdocnum = fMbdocnum;
        this.fMbambnum = fMbambnum;
        this.fMbfirnum = fMbfirnum;
        this.fMbinfernum = fMbinfernum;
        this.fMbmeaker = fMbmeaker;
        this.fMbmakertel = fMbmakertel;
    }

    public ModelEntity() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model.fk_mbid
     *
     * @return the value of t_model.fk_mbid
     *
     * @mbggenerated
     */
    public Integer getFkMbid() {
        return fkMbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model.f_mbName
     *
     * @return the value of t_model.f_mbName
     *
     * @mbggenerated
     */
    public String getfMbname() {
        return fMbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model.f_mbType
     *
     * @return the value of t_model.f_mbType
     *
     * @mbggenerated
     */
    public String getfMbtype() {
        return fMbtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model.f_mbRank
     *
     * @return the value of t_model.f_mbRank
     *
     * @mbggenerated
     */
    public String getfMbrank() {
        return fMbrank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model.f_mbDocNum
     *
     * @return the value of t_model.f_mbDocNum
     *
     * @mbggenerated
     */
    public Integer getfMbdocnum() {
        return fMbdocnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model.f_mbAmbNum
     *
     * @return the value of t_model.f_mbAmbNum
     *
     * @mbggenerated
     */
    public Integer getfMbambnum() {
        return fMbambnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model.f_mbFirNum
     *
     * @return the value of t_model.f_mbFirNum
     *
     * @mbggenerated
     */
    public Integer getfMbfirnum() {
        return fMbfirnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model.f_mbInferNum
     *
     * @return the value of t_model.f_mbInferNum
     *
     * @mbggenerated
     */
    public Integer getfMbinfernum() {
        return fMbinfernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model.f_mbMeaker
     *
     * @return the value of t_model.f_mbMeaker
     *
     * @mbggenerated
     */
    public String getfMbmeaker() {
        return fMbmeaker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model.f_mbMakerTel
     *
     * @return the value of t_model.f_mbMakerTel
     *
     * @mbggenerated
     */
    public String getfMbmakertel() {
        return fMbmakertel;
    }

	public void setFkMbid(Integer fkMbid) {
		this.fkMbid = fkMbid;
	}

	public void setfMbname(String fMbname) {
		this.fMbname = fMbname;
	}

	public void setfMbtype(String fMbtype) {
		this.fMbtype = fMbtype;
	}

	public void setfMbrank(String fMbrank) {
		this.fMbrank = fMbrank;
	}

	public void setfMbdocnum(Integer fMbdocnum) {
		this.fMbdocnum = fMbdocnum;
	}

	public void setfMbambnum(Integer fMbambnum) {
		this.fMbambnum = fMbambnum;
	}

	public void setfMbfirnum(Integer fMbfirnum) {
		this.fMbfirnum = fMbfirnum;
	}

	public void setfMbinfernum(Integer fMbinfernum) {
		this.fMbinfernum = fMbinfernum;
	}

	public void setfMbmeaker(String fMbmeaker) {
		this.fMbmeaker = fMbmeaker;
	}

	public void setfMbmakertel(String fMbmakertel) {
		this.fMbmakertel = fMbmakertel;
	}
    
}