package com.lovo.bean;

public class ZyEntity {
	
    public void setPkId(Integer pkId) {
		this.pkId = pkId;
	}

	public void setfZyname(String fZyname) {
		this.fZyname = fZyname;
	}

	public void setfZyadd(String fZyadd) {
		this.fZyadd = fZyadd;
	}

	public void setfZytype(String fZytype) {
		this.fZytype = fZytype;
	}

	public void setfZyurl(String fZyurl) {
		this.fZyurl = fZyurl;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zy.pk_id
     *
     * @mbggenerated
     */
    private Integer pkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zy.f_zyName
     *
     * @mbggenerated
     */
    private String fZyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zy.f_zyAdd
     *
     * @mbggenerated
     */
    private String fZyadd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zy.f_zyType
     *
     * @mbggenerated
     */
    private String fZytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zy.f_zyURL
     *
     * @mbggenerated
     */
    private String fZyurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zy
     *
     * @mbggenerated
     */
    public ZyEntity(Integer pkId, String fZyname, String fZyadd, String fZytype, String fZyurl) {
        this.pkId = pkId;
        this.fZyname = fZyname;
        this.fZyadd = fZyadd;
        this.fZytype = fZytype;
        this.fZyurl = fZyurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zy.pk_id
     *
     * @return the value of t_zy.pk_id
     *
     * @mbggenerated
     */
    public Integer getPkId() {
        return pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zy.f_zyName
     *
     * @return the value of t_zy.f_zyName
     *
     * @mbggenerated
     */
    public String getfZyname() {
        return fZyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zy.f_zyAdd
     *
     * @return the value of t_zy.f_zyAdd
     *
     * @mbggenerated
     */
    public String getfZyadd() {
        return fZyadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zy.f_zyType
     *
     * @return the value of t_zy.f_zyType
     *
     * @mbggenerated
     */
    public String getfZytype() {
        return fZytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zy.f_zyURL
     *
     * @return the value of t_zy.f_zyURL
     *
     * @mbggenerated
     */
    public String getfZyurl() {
        return fZyurl;
    }
}