package com.lovo.mapper;

import com.lovo.bean.ManageEntity;
import com.lovo.bean.ManageShowEntity;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ManageShowEntityMapper {
	
	
    @Select({
        "select",
        "pk_tId, fk_thingId, fk_id, f_hosName, f_add, f_peoNum, f_carNum, f_mainPeo, ",
        "f_time, f_yardman, f_mainPeoTel, f_dealType, f_zyType",
        "from t_manageshow",
        "where f_time = #{param1} and f_zyType = #{param2}"
    })
    @ResultMap("BaseResultMap")
	public ManageShowEntity findbytime(String date,String type);
	
    @Select({
        "select",
        "pk_tId, fk_thingId, fk_id, f_hosName, f_add, f_peoNum, f_carNum, f_mainPeo, ",
        "f_time, f_yardman, f_mainPeoTel, f_dealType, f_zyType",
        "from t_manageshow",
        "where fk_thingId = #{ManagerId}"
    })
    @ResultMap("BaseResultMap")
	public List<ManageShowEntity> findManagerById(String ManagerId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manageshow
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_manageshow",
        "where pk_tId = #{pkTid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer pkTid);

    @Insert({
        "insert into t_manageshow (fk_thingId, ",
        "fk_id, f_hosName, ",
        "f_add, f_peoNum, f_carNum, ",
        "f_mainPeo, f_time, ",
        "f_yardman, f_mainPeoTel, ",
        "f_dealType, f_zyType)",
        "values (#{fkThingid,jdbcType=VARCHAR}, ",
        "#{fkId,jdbcType=VARCHAR}, #{fHosname,jdbcType=VARCHAR}, ",
        "#{fAdd,jdbcType=VARCHAR}, #{fPeonum,jdbcType=INTEGER}, #{fCarnum,jdbcType=INTEGER}, ",
        "#{fMainpeo,jdbcType=VARCHAR}, #{fTime,jdbcType=VARCHAR}, ",
        "#{fYardman,jdbcType=VARCHAR}, #{fMainpeotel,jdbcType=VARCHAR}, ",
        "#{fDealtype,jdbcType=VARCHAR}, #{fZytype,jdbcType=VARCHAR})"
    })
    public void addManageShow(ManageShowEntity mse);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manageshow
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_manageshow (pk_tId, fk_thingId, ",
        "fk_id, f_hosName, ",
        "f_add, f_peoNum, f_carNum, ",
        "f_mainPeo, f_time, ",
        "f_yardman, f_mainPeoTel, ",
        "f_dealType, f_zyType)",
        "values (#{pkTid,jdbcType=INTEGER}, #{fkThingid,jdbcType=VARCHAR}, ",
        "#{fkId,jdbcType=VARCHAR}, #{fHosname,jdbcType=VARCHAR}, ",
        "#{fAdd,jdbcType=VARCHAR}, #{fPeonum,jdbcType=INTEGER}, #{fCarnum,jdbcType=INTEGER}, ",
        "#{fMainpeo,jdbcType=VARCHAR}, #{fTime,jdbcType=VARCHAR}, ",
        "#{fYardman,jdbcType=VARCHAR}, #{fMainpeotel,jdbcType=VARCHAR}, ",
        "#{fDealtype,jdbcType=VARCHAR}, #{fZytype,jdbcType=VARCHAR})"
    })
    int insert(ManageShowEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manageshow
     *
     * @mbggenerated
     */
    int insertSelective(ManageShowEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manageshow
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "pk_tId, fk_thingId, fk_id, f_hosName, f_add, f_peoNum, f_carNum, f_mainPeo, ",
        "f_time, f_yardman, f_mainPeoTel, f_dealType, f_zyType",
        "from t_manageshow",
        "where fk_thingId = #{thingsid,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")

    ManageShowEntity selectByPrimaryKey1(Integer pkTid);
    
    @Select({
        "select",
        "pk_tId, fk_thingId, fk_id, f_hosName, f_add, f_peoNum, f_carNum, f_mainPeo, ",
        "f_time, f_yardman, f_mainPeoTel, f_dealType, f_zyType",
        "from t_manageshow",
        "where fk_thingId = #{thingsid,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    ManageShowEntity selectByPrimaryKey(String thingsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manageshow
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManageShowEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manageshow
     *
     * @mbggenerated
     */
    @Update({
        "update t_manageshow",
        "set fk_thingId = #{fkThingid,jdbcType=VARCHAR},",
          "fk_id = #{fkId,jdbcType=VARCHAR},",
          "f_hosName = #{fHosname,jdbcType=VARCHAR},",
          "f_add = #{fAdd,jdbcType=VARCHAR},",
          "f_peoNum = #{fPeonum,jdbcType=INTEGER},",
          "f_carNum = #{fCarnum,jdbcType=INTEGER},",
          "f_mainPeo = #{fMainpeo,jdbcType=VARCHAR},",
          "f_time = #{fTime,jdbcType=VARCHAR},",
          "f_yardman = #{fYardman,jdbcType=VARCHAR},",
          "f_mainPeoTel = #{fMainpeotel,jdbcType=VARCHAR},",
          "f_dealType = #{fDealtype,jdbcType=VARCHAR},",
          "f_zyType = #{fZytype,jdbcType=VARCHAR}",
        "where pk_tId = #{pkTid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ManageShowEntity record);
    
  
    public List<ManageShowEntity> findAll(@Param("zyType") String zyType,@Param("thingsId")String thingsId);
}