package com.lovo.mapper;

import com.lovo.bean.ManageEntity;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ManageEntityMapper {
  
	public List<ManageEntity> findManagerByType(@Param("type")String type);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_manage",
        "where f_zyxqId = #{fZyxqid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer fZyxqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_manage (f_zyxqId, fk_zyId, ",
        "f_zyName, f_timeOut, ",
        "f_timeBack, f_zyStuse)",
        "values (#{fZyxqid,jdbcType=INTEGER}, #{fkZyid,jdbcType=VARCHAR}, ",
        "#{fZyname,jdbcType=VARCHAR}, #{fTimeout,jdbcType=VARCHAR}, ",
        "#{fTimeback,jdbcType=VARCHAR}, #{fZystuse,jdbcType=VARCHAR})"
    })
    int insert(ManageEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage
     *
     * @mbggenerated
     */
    int insertSelective(ManageEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "f_zyxqId, fk_zyId, f_zyName, f_timeOut, f_timeBack, f_zyStuse",
        "from t_manage",
        "where fk_zyId = #{fZyid,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    List<ManageEntity> selectByZyId(String fZyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManageEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage
     *
     * @mbggenerated
     */
    @Update({
        "update t_manage",
        "set fk_zyId = #{fkZyid,jdbcType=VARCHAR},",
          "f_zyName = #{fZyname,jdbcType=VARCHAR},",
          "f_timeOut = #{fTimeout,jdbcType=VARCHAR},",
          "f_timeBack = #{fTimeback,jdbcType=VARCHAR},",
          "f_zyStuse = #{fZystuse,jdbcType=VARCHAR}",
        "where f_zyxqId = #{fZyxqid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ManageEntity record);
    
    @Update({
        "update t_manage ",
       
          "set f_timeBack = #{returntime,jdbcType=VARCHAR},",
          "f_zyStuse = #{zyStuse,jdbcType=VARCHAR}",
        "where fk_zyId = #{fkZyid,jdbcType=VARCHAR} and f_zyName=#{fZyname,jdbcType=VARCHAR}"
    })
    public void updateByzyidAndZyname(@Param("fkZyid")String fkZyid,@Param("fZyname")String fZyname,
    		@Param("returntime")String returntime,@Param("zyStuse")String zyStuse);
}