package com.lovo.mapper;

import com.lovo.bean.PublicEntity;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PublicEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_public
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_public",
        "where pk_id = #{pkId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_public
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_public (pk_id, f_type, ",
        "f_key, f_value)",
        "values (#{pkId,jdbcType=INTEGER}, #{fType,jdbcType=VARCHAR}, ",
        "#{fKey,jdbcType=INTEGER}, #{fValue,jdbcType=VARCHAR})"
    })
    int insert(PublicEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_public
     *
     * @mbggenerated
     */
    int insertSelective(PublicEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_public
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "pk_id, f_type, f_key, f_value",
        "from t_public",
        "where pk_id = #{pkId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    PublicEntity selectByPrimaryKey(Integer pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_public
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PublicEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_public
     *
     * @mbggenerated
     */
    @Update({
        "update t_public",
        "set f_type = #{fType,jdbcType=VARCHAR},",
          "f_key = #{fKey,jdbcType=INTEGER},",
          "f_value = #{fValue,jdbcType=VARCHAR}",
        "where pk_id = #{pkId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PublicEntity record);
    @Select({
    	"select",
        "pk_id, f_type, f_key, f_value",
        "from t_public"
    })
    @ResultMap("BaseResultMap")
    public List<PublicEntity> findAll();
}